@startuml LvcClientStaticStructure

left to right direction
skinparam linetype ortho

page 1x2
skinparam pageMargin 10
skinparam pageExternalColor gray
skinparam pageBorderColor black

title LVC Client


' External Interfaces

' Server Interfaces

package "<<node>> LVC Server" {
  interface IAuthHandler
  interface IFLManager
  interface IRandomUserMatcher
  interface IVoCHandler
  interface IUserBanNotifier
  interface ISubscriptionManager
  interface IVChatActivityListener
}

package "<<node>> Dispatcher Server" {
  interface IDispatcherServer
}

together {
  interface IVChatRequestHandler
  interface INetStreamSource
}

interface IAdsService

package "<<node>> LVC Client" {

  interface IOnDeviceMLEngine
  interface ICrypto
  interface ICamera

  together {
    interface IDispatcherClient
  }

  together {
    interface ICamStreamSink
    interface INetStreamSink
    interface IVChatManager
    interface IStreamEventNotifier
  }

    package "Dispatcher Package" {
      component DispatcherClient
      component LvcServerAddressCache
    
      IDispatcherServer )- DispatcherClient
    }

    interface IVChatStreamManager
    interface ILocalMLManager

    package "Stream Package" {
      component VChatStreamManager
      component StreamEventNotifier
      
      component CamStreamSource
      component NetStreamSource
      ICrypto )- NetStreamSource
      
      component CamStreamSink
      component NetStreamSink
  
      component CamFilterFeature
      component GramCorrFeature
  		component TopicSuggFeature
  		component XlationFeature
  		component WarnMalUserFeature

  		ICamera )- CamStreamSource
  		CamStreamSource -0)- CamFilterFeature : IPullFilter
  		CamFilterFeature -0)- GramCorrFeature : IPullFilter
  		GramCorrFeature -0)- CamStreamSink : IPullFilter
  		INetStreamSource )- CamStreamSink
  
  		NetStreamSource -0)- XlationFeature : IPullFilter
  		XlationFeature -0)- TopicSuggFeature : IPullFilter
  		TopicSuggFeature -0)- WarnMalUserFeature : IPullFilter
  		WarnMalUserFeature -0)- NetStreamSink : IPullFilter
  
      IVChatRequestHandler )- VChatStreamManager
    }

    
    package "MachineLearning Package" {
      component LocalMLManager
      database FeatureDB
      database ModelStorage
    }
  
    package "Control Package" {
      component VChatManager
      component VChatRequestHandler
      component SubscriptionController
      component UserBanHandler
      database UserConfigStorage
      
      IDispatcherClient )- VChatManager
      IAuthHandler )- VChatManager
      IRandomUserMatcher )- VChatManager
      IVChatStreamManager )- VChatManager
      IVoCHandler )- VChatManager
      IVChatActivityListener )- VChatManager

      IUserBanNotifier )- UserBanHandler
      ILocalMLManager )- UserBanHandler

      IVChatStreamManager )- VChatRequestHandler
      
      IVChatStreamManager )- SubscriptionController
      ISubscriptionManager )- SubscriptionController
      
    }
  
    VChatStreamManager -() IVChatStreamManager
  
    LocalMLManager -() ILocalMLManager
    
    ILocalMLManager )- WarnMalUserFeature
    IVoCHandler )- WarnMalUserFeature

    component ClientUI
  	INetStreamSink )- ClientUI
  	ICamStreamSink )- ClientUI
  	IVChatManager )- ClientUI
  	IStreamEventNotifier )- ClientUI

  DispatcherClient -() IDispatcherClient

  CamStreamSink -() ICamStreamSink
  NetStreamSink -() INetStreamSink
  VChatManager -() IVChatManager
  StreamEventNotifier -() IStreamEventNotifier

  IFLManager )- LocalMLManager
  IOnDeviceMLEngine )- LocalMLManager
}

VChatRequestHandler -() IVChatRequestHandler
NetStreamSource -() INetStreamSource

IAdsService )- ClientUI

"Dispatcher Package" -[hidden]- "Control Package"
"Control Package" -[hidden]- "MachineLearning Package"
' IUserBanNotifier -[hidden]- IRandomUserMatcher
' IRandomUserMatcher -[hidden]- IAuthHandler
' IAuthHandler -[hidden]- IFLManager
' IFLManager -[hidden]- IVoCHandler
' IVoCHandler -[hidden]- IUserBanNotifier
' IUserBanNotifier -[hidden]- ISubscriptionManager

"<<node>> LVC Server" --[hidden]- "<<node>> Dispatcher Server"
' "<<node>> LVC Server" -[hidden]left- "<<node>> LVC Client"

@enduml
