@startuml

skinparam wrapWidth 100
left to right direction
skinparam linetype ortho

actor "사용자" as User
actor "운영자" as Admin
actor "개발자" as Developer
together {
    actor "광고 플랫폼" as AdProvider
    actor "결제 대행사" as PayProvider
}

package "LVC (시스템)" {
    together {
        usecase "UC-01 회원가입 및 로그인" as UC01
        usecase "UC-02 평점 및 VoC 등록" as UC02
        usecase "UC-03 프리미엄 서비스 구독" as UC03
        usecase "UC-04 프리미엄 서비스 구독 취소" as UC04
        usecase "UC-05 광고 제공" as UC05
        usecase "UC-06 친구 추가" as UC06
        usecase "UC-07 친구 삭제" as UC07
        usecase "UC-08 랜덤 비디오 챗 시작 요청" as UC08
        usecase "UC-09 친구 비디오 챗 시작 요청" as UC09
        usecase "UC-10 비디오 챗 부가기능 설정" as UC10
        usecase "UC-11 비디오 챗 종료 요청" as UC11
        usecase "UC-12 위험 대화 상대 경고" as UC12
    }
    together {
        usecase UC13 as "UC-13 사용자 차단
        ..Extension Points..
        차단 대상이 챗중
        "
        usecase "UC-14 사용자 통계" as UC14
        usecase "UC-15 VoC 브라우징" as UC15
        usecase "UC-16 장애 알림" as UC16

        ' put things together
        UC16 -[hidden] UC15
        UC15 -[hidden] UC14
        UC14 -[hidden] UC13
    }
    together {
        usecase "UC-17 비디오 챗 시작" as UC17
        usecase "UC-18 비디오 챗 종료" as UC18
    }
    together {
        usecase "UC-19 AI 모델 업데이트" as UC19
        usecase "UC-20 AI 모델 자동 평가" as UC20

        ' put things together
        UC19 -[hidden] UC20
    }

    UC05 --> User
    UC12 --> User
    
    User --> UC01
    User --> UC02
    User --> UC03
    User --> UC04
    User --> UC06
    User --> UC07
    User --> UC08
    User --> UC09
    User --> UC11
    User --> UC10
    
    Admin -up-> UC13
    Admin -up-> UC14
    Admin -up-> UC15
    Admin -up-> UC16

    UC03 --down-> PayProvider
    UC04 --down-> PayProvider

    UC05 --down-> AdProvider
    
    UC08 ..> UC17 : "<<include>>"
    UC09 ..> UC17 : "<<include>>"
    UC11 ..> UC18 : "<<include>>"
    UC18 .> UC13 : "<<extend>>"

    Developer -up-> UC19
    Developer -up-> UC20

    UC19 -[hidden] UC18
}

@enduml
